# Generated by Django 4.1.7 on 2023-04-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category_id',
        ),
    ]
